# Generated by Django 6.0.2 on 2026-02-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catagory_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=225)),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/catagories/')),
            ],
            options={
                'verbose_name': 'catagory',
                'verbose_name_plural': 'Catagories',
            },
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
