# Generated by Django 6.0.2 on 2026-02-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0002_catagory_delete_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='Catagory_name',
            new_name='catagory_name',
        ),
        migrations.AlterField(
            model_name='catagory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
